appname: "ajtest"

layout:   main
charset:  UTF-8
template: template_toolkit
logger:   Console

engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'
  logger:
    Console:
      log_level:  debug
      log_format: '[%f l.%l] %m'
